variables:
  DOCKER_DRIVER: overlay2
  SOURCE: "."
  PRODUCTION_BRANCH: "master"
image: node: v12.17.0
stages:
  - test
  - build
before_script:
  - "mkdir -p ~/.ssh"
  - 'echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa'
  - "chmod 600 ~/.ssh/id_rsa"
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
PackageTest:
  stage: test
  script:
    - echo "Building production package and deploying production environment"
    - npm test
  environment:
    name: testing
  only:
    - $PRODUCTION_BRANCH
PackageBuild:
  stage: build
  script:
    - echo "Building production package and deploying production environment"
  environment:
    name: production
  only:
    - $PRODUCTION_BRANCH
