variables:
  DOCKER_DRIVER: overlay2
  SOURCE: "."
image: node:12.17.0
cache:
  paths:
    - node_modules/
stages:
  - test
  - build
before_script:
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
PackageTest:
  stage: test
  before_script:
    - npm install --frozen-lockfile
  script:
    - echo "Testing"
    - npm test
  environment:
    name: testing
  only:
    - master
PackageBuild:
  stage: build
  script:
    - echo "Building production package and deploying production environment"
    - npm -v
  environment:
    name: building
  only:
    - master

